### ISSUE TITLE
Add nodeSelector option to values file

### ISSUE THREAD

**Issue by cberge908** [cloudquery/helm-charts#260]
### Describe the resource.

It would be nice to pass a node selector to the deployment/ cronjob where CQ should run. At the moment it's only possible by adding the nodeSelector manually after initial deployment via helm.

### Use Case

Heavy CQ job should run on a dedicated node where it's not expected that the job/ pod get OOMkilled.

**Comment by erezrokah** [comment]
Hi @cberge908, thanks for opening the issue 🚀 We'd be happy to also accept a contirubiton for this

**Comment by erezrokah** [comment]
Resolved by https://github.com/cloudquery/helm-charts/pull/269 thanks @cberge908, great work 🚀
