### ISSUE TITLE
[FR] additional configmap

### ISSUE THREAD

**Issue by Hokwang** [cloudquery/helm-charts#265]
### Describe the resource.

Hi,

This is feature request.

Please add the way to add more configmap and mount it.

For example,
I need to create aws config file,
```
[profile A]
xxx
```

and it should be ~/.aws/config

### Use Case

I think that user need like this
```
extraConfigmap:
  awsconfig: |
    [profile A]
    role_arn=xxx
    ...
```

**Comment by yevgenypats** [comment]
Closing as stale
