### ISSUE TITLE
404 When Linking to Docs

### ISSUE THREAD

**Issue by jasonscalia** [cloudquery/helm-charts#36]
### Describe the bug

Link to documentation returns a 404: https://docs.cloudquery.io/docs/deployment/helm-chart

### Expected Behavior

Link should return current docs for the helm-chart.

### Steps to Reproduce

Click the below link in Readme:

Documentation and tutorial can be found here [docs.cloudquery.io](https://docs.cloudquery.io/docs/deployment/helm-chart).

### Provider and CloudQuery version

Latest in main

**Comment by yevgenypats** [comment]
Thank! Yeah the docs are actually here https://github.com/cloudquery/helm-charts/tree/main/charts/cloudquery and I need also to add more. I moved the to the README because they are also being indexed here - https://artifacthub.io/packages/helm/cloudquery/cloudquery
