### ISSUE TITLE
Enable User to Specify CQ Version

### ISSUE THREAD

**Issue by bbernays** [cloudquery/helm-charts#74]
Right now `appVersion` is hardcoded, without users downloading the repo, editing the chart and then installing the chart there is no way for users to be able to specify the version they want to install.

CloudQuery should have a default supported version in the Helm Chart, but users should be able to overwrite that if they want to

**Comment by yevgenypats** [comment]
AppVersion cannot be overridden but users can override `.Values.image.tag` can be. See
https://stackoverflow.com/questions/69817305/how-set-field-app-version-in-helm3-chart
https://github.com/cloudquery/helm-charts/blob/main/charts/cloudquery/templates/cronjob.yaml#L26

**Comment by yevgenypats** [comment]
Looks like `image.tag` is missing from the documentation - we will need to fix it :)

**Comment by spangenberg** [comment]
Fixed with https://github.com/cloudquery/helm-charts/pull/77
