### ISSUE TITLE
Support Yaml Configuration Files

### ISSUE THREAD

**Issue by bbernays** [cloudquery/helm-charts#75]
In `v0.30` and above all configurations for CQ  are stored by default in a yaml file. The managed Helm chart should enable users to stay up to date with releases if they want to

**Comment by yevgenypats** [comment]
This is not updated - https://github.com/cloudquery/helm-charts/blob/main/charts/cloudquery/values.yaml

**Comment by spangenberg** [comment]
Fixed with https://github.com/cloudquery/helm-charts/pull/76
